### ISSUE TITLE
Transition to PEP 517

### ISSUE THREAD

**Issue by Molkree** [Ocean-Data-Lab/ooipy#106]
It would be nice to transition to [PEP 517](https://www.python.org/dev/peps/pep-0517/) builds using `pyproject.toml` and move to `setup.cfg` from `setup.py`.
This [setuptools guide](https://setuptools.pypa.io/en/latest/userguide/quickstart.html) should be a good start.

**Comment by John-Ragland** [comment]
This is definitely not my area of expertise haha, but if you think this would be a good idea, go for it!

**Comment by John-Ragland** [comment]
closing this for now
