### ISSUE TITLE
bb get_acoustic data might be broken

### ISSUE THREAD

**Issue by John-Ragland** [Ocean-Data-Lab/ooipy#118]
```
import ooipy
from datetime import datetime

start_time = datetime(2021,6,24,21)
end_time = datetime(2021,6,25,2)
hdata = ooipy.request.hydrophone_request.get_acoustic_data(start_time, end_time, node='PC03A')
```

hdata is none type. But there is clearly data in the raw data server (see https://rawdata-west.oceanobservatories.org/files/RS03AXPS/PC03A/08-HYDBBA303/2021/06/24/)

**Comment by satan-j** [comment]
I also encountered the same problem. What time periods of data are useful?
