### ISSUE TITLE
Error with get_acoustic_data(_LF)

### ISSUE THREAD

**Issue by John-Ragland** [Ocean-Data-Lab/ooipy#132]
Looks like get_acoustic_data, and get_acoustic_data_LF are only returning None.

This is likely due to the reorg from OOIs side of how they are storing their data.

**Comment by ainsleylaiuw** [comment]
I encountered this issue while trying to query some recorded AIS data timestamps and tried running some code from the demo notebook to see if it was just my own implementation error or if something went wrong with the query itself. Below was the code I used from the demo notebook.

```python
import datetime
start_time = datetime.datetime(2017,7,1,0,0,0)
end_time = datetime.datetime(2017,7,1,0,1,0)
node1 = 'LJ01D'
node2 = 'Eastern_Caldera'

print('Downloading Low Frequency Data:')
hdata_lowfreq = ooipy.get_acoustic_data_LF(start_time, end_time, node2, verbose=True, zero_mean=True)
print(hdata_lowfreq.stats)
```

which returns the following:
```
Downloading Low Frequency Data:
Downloading mseed file...
   Specific Time window timed out.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\UserALai\Documents\Work\Ocean Data\OcDa-Files\Untitled-1.ipynb Cell 18' in <cell line: 9>()
      7 print('Downloading Low Frequency Data:')
      8 hdata_lowfreq = ooipy.get_acoustic_data_LF(start_time, end_time, node2, verbose=True, zero_mean=True)
----> 9 print(hdata_lowfreq.stats)

AttributeError: 'NoneType' object has no attribute 'stats'
```

**Comment by John-Ragland** [comment]
Running your same code, I don't get an error
What version of ooipy are you running?

**Comment by ainsleylaiuw** [comment]
I had been using v1.1.4
Just upgraded to v1.1.5 and the code block seems to run without error

**Comment by satan-j** [comment]
I get an error in running v1.1.5，below was the code.
`import ooipy
import datetime
from matplotlib import pyplot as plt

# Specify start time, end time, and node for data download (1 minutes of data)
# Download Broadband data
start_time = datetime.datetime(2017,7,1,0,0,0)
end_time = datetime.datetime(2017,7,1,0,1,0)
node1 = 'LJ01D'
print('Downloading Broadband Data:')
hdata_broadband = ooipy.get_acoustic_data(start_time, end_time, node1, verbose=True)
print(hdata_broadband.stats)`

returns the following:

`Cannot connect to host rawdata.oceanobservatories.org:443 ssl:default [Connect call failed ('128.193.196.13', 443)]
No data available for specified day and node. Please change the day or use a different node`

how to solve it? and the same code in Low Frequency can run right.
