### ISSUE TITLE
Add tutorial that runs in binder

### ISSUE THREAD

**Issue by John-Ragland** [Ocean-Data-Lab/ooipy#144]
This would be a great way to create a tutorial for how to use ooipy!

**Comment by lsetiawan** [comment]
Just an fyi for you before going to far to the `binder` route. The jupyter team is scaling down mybinder: https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f

**Comment by John-Ragland** [comment]
@lsetiawan, Thanks for this! Probably shouldn't prioritize it for now.
