### ISSUE TITLE
Connect call failed ('128.193.196.13', 443)

### ISSUE THREAD

**Issue by satan-j** [Ocean-Data-Lab/ooipy#148]
I get an error in running v1.1.5，below was the code.
`
import ooipy import datetime from matplotlib import pyplot as plt start_time = datetime.datetime(2017,7,1,0,0,0) end_time = datetime.datetime(2017,7,1,0,1,0) node1 = 'LJ01D' print('Downloading Broadband Data:') hdata_broadband = ooipy.get_acoustic_data(start_time, end_time, node1, verbose=True) print(hdata_broadband.stats)
`

returns the following:

`
Cannot connect to host rawdata.oceanobservatories.org:443 ssl:default [Connect call failed ('128.193.196.13', 443)] No data available for specified day and node. Please change the day or use a different node
`

how to solve it? and the same code in Low Frequency can run right.

**Comment by John-Ragland** [comment]
I'm not completely sure what could be causing this. I'm not able to reproduce on my end. Have you again / did you have a reliable internet connection when executing this code?

**Comment by satan-j** [comment]
I can open the VPN in the browser to access this url“https://[rawdata-west.oceanobservatories.org/files/?C=M;O=A](https://rawdata-west.oceanobservatories.org/files/?C=M;O=A)”, but even if I set VPN to global mode, python is still unable to connect this url, could you please tell me what's the solution
