### ISSUE TITLE
updating the packaging

### ISSUE THREAD

**Issue by John-Ragland** [Ocean-Data-Lab/ooipy#149]
You need to add it under `install_requires` for listing dependency. The second section with `[isort]` is settings for `isort` a library that checks and sorts import statements. Not sure why this specification is needed. The packaging aspects will probably need to be updated in separate PR at some point.

```
...
install_requires =
    obspy
    fsspec==2022.11.0
    aiohttp
    pandas
    numpy<1.22
    lxml
    xarray
```

_Originally posted by @lsetiawan in https://github.com/Ocean-Data-Lab/ooipy/issues/147#issuecomment-1650492484_

**Comment by John-Ragland** [comment]
@lsetiawan do you have specific suggestions on how we might should change the packaging for ooipy? 
We've been working on a bigger update to v1.2.0, where we're adding a good bit of functionality. And it'd probably make sense to do this for this update.

Also, this will probably be a good time to get rid of our numpy<1.22 requirement and test that it doesn't break anything.

**Comment by lsetiawan** [comment]
@John-Ragland just to let you know that the latest version of xarray do require python 3.9 and greater and your package currently is pinned to be `>=3.7`, which means that if users installs your package with python `3.7` they won't be using the latest xarray. If ooipy works with python `>=3.9` then let's update that and start using python >=3.9 for development.

**Comment by lsetiawan** [comment]
Here's a recommended guide for developing scientific python package that you should read and follow: https://learn.scientific-python.org/development/. It's made by the greater scientific python community. The specific packaging guide can be found [here](https://learn.scientific-python.org/development/guides/packaging-simple/). It would be a pretty huge overhaul, I can help guide you guys if you'd like to make this happen.

**Comment by John-Ragland** [comment]
> @John-Ragland just to let you know that the latest version of xarray do require python 3.9 and greater and your package currently is pinned to be `>=3.7`, which means that if users installs your package with python `3.7` they won't be using the latest xarray. If ooipy works with python `>=3.9` then let's update that and start using python >=3.9 for development.

I think that's a good idea. OOIPy should work with 3.9
